// Themes with hasLightDark: true have a `light` and `dark` sub-object.
// The dark mode toggle switches between them (both UI chrome AND canvas).
// Themes with hasLightDark: false are single-mode — toggle is disabled.

export const THEMES = {
    default: {
        label: 'Default',
        hasLightDark: true,
        dark: {
            ui: {
                '--bg-color': '#0f0f0f',
                '--toolbar-bg': '#1a1a1a',
                '--toolbar-bg-end': '#141414',
                '--toolbar-hover': '#252525',
                '--text-color': '#e5e5e5',
                '--text-muted': '#737373',
                '--accent-color': '#6366f1',
                '--accent-hover': '#818cf8',
                '--accent-gradient-end': '#4f46e5',
                '--border-color': '#2a2a2a',
                '--danger-color': '#ef4444',
                '--canvas-area-bg-center': '#1a1a1a',
                '--canvas-area-bg-edge': '#0a0a0a',
                '--hover-bg': '#333333',
                '--hover-border': '#444444',
            },
            canvas: { bg: '#ffffff', dot: '#d0d0d0' },
        },
        light: {
            ui: {
                '--bg-color': '#f5f5f5',
                '--toolbar-bg': '#ffffff',
                '--toolbar-bg-end': '#f0f0f0',
                '--toolbar-hover': '#e8e8e8',
                '--text-color': '#1a1a1a',
                '--text-muted': '#737373',
                '--accent-color': '#6366f1',
                '--accent-hover': '#818cf8',
                '--accent-gradient-end': '#4f46e5',
                '--border-color': '#d4d4d4',
                '--danger-color': '#ef4444',
                '--canvas-area-bg-center': '#ebebeb',
                '--canvas-area-bg-edge': '#e0e0e0',
                '--hover-bg': '#dcdcdc',
                '--hover-border': '#c0c0c0',
            },
            canvas: { bg: '#ffffff', dot: '#d0d0d0' },
        },
    },
    'base16-atelier': {
        label: 'Atelier',
        hasLightDark: false,
        ui: {
            '--bg-color': '#20201d',
            '--toolbar-bg': '#292824',
            '--toolbar-bg-end': '#232220',
            '--toolbar-hover': '#3a3830',
            '--text-color': '#a6a28c',
            '--text-muted': '#7d7a68',
            '--accent-color': '#6684e1',
            '--accent-hover': '#b854d4',
            '--accent-gradient-end': '#5570c4',
            '--border-color': '#6e6b5e',
            '--danger-color': '#d73737',
            '--canvas-area-bg-center': '#292824',
            '--canvas-area-bg-edge': '#1a1a17',
            '--hover-bg': '#47443a',
            '--hover-border': '#7d7a68',
        },
        canvas: { bg: '#fefbec', dot: '#d0cdb8' },
    },
    'base16-eighties': {
        label: 'Eighties',
        hasLightDark: false,
        ui: {
            '--bg-color': '#2d2d2d',
            '--toolbar-bg': '#393939',
            '--toolbar-bg-end': '#2f2f2f',
            '--toolbar-hover': '#515151',
            '--text-color': '#d3d0c8',
            '--text-muted': '#747369',
            '--accent-color': '#6699cc',
            '--accent-hover': '#cc99cc',
            '--accent-gradient-end': '#5588bb',
            '--border-color': '#515151',
            '--danger-color': '#f2777a',
            '--canvas-area-bg-center': '#393939',
            '--canvas-area-bg-edge': '#232323',
            '--hover-bg': '#5f5f5f',
            '--hover-border': '#747369',
        },
        canvas: { bg: '#f2f0ec', dot: '#d3d0c8' },
    },
    catppuccin: {
        label: 'Catppuccin',
        hasLightDark: false,
        ui: {
            '--bg-color': '#1e1e2e',
            '--toolbar-bg': '#181825',
            '--toolbar-bg-end': '#14141f',
            '--toolbar-hover': '#313244',
            '--text-color': '#cdd6f4',
            '--text-muted': '#6c7086',
            '--accent-color': '#cba6f7',
            '--accent-hover': '#f5c2e7',
            '--accent-gradient-end': '#b48de0',
            '--border-color': '#45475a',
            '--danger-color': '#f38ba8',
            '--canvas-area-bg-center': '#1e1e2e',
            '--canvas-area-bg-edge': '#11111b',
            '--hover-bg': '#3d3f56',
            '--hover-border': '#585b70',
        },
        canvas: { bg: '#eff1f5', dot: '#ccd0da' },
    },
    gruvbox: {
        label: 'Gruvbox',
        hasLightDark: true,
        dark: {
            ui: {
                '--bg-color': '#282828',
                '--toolbar-bg': '#1d2021',
                '--toolbar-bg-end': '#191b1c',
                '--toolbar-hover': '#3c3836',
                '--text-color': '#ebdbb2',
                '--text-muted': '#a89984',
                '--accent-color': '#458588',
                '--accent-hover': '#83a598',
                '--accent-gradient-end': '#3a7275',
                '--border-color': '#3c3836',
                '--danger-color': '#fb4934',
                '--canvas-area-bg-center': '#282828',
                '--canvas-area-bg-edge': '#1d2021',
                '--hover-bg': '#504945',
                '--hover-border': '#665c54',
            },
            canvas: { bg: '#fbf1c7', dot: '#d5c4a1' },
        },
        light: {
            ui: {
                '--bg-color': '#fbf1c7',
                '--toolbar-bg': '#f2e5bc',
                '--toolbar-bg-end': '#ebdbb2',
                '--toolbar-hover': '#ebdbb2',
                '--text-color': '#3c3836',
                '--text-muted': '#7c6f64',
                '--accent-color': '#458588',
                '--accent-hover': '#83a598',
                '--accent-gradient-end': '#3a7275',
                '--border-color': '#d5c4a1',
                '--danger-color': '#cc241d',
                '--canvas-area-bg-center': '#f9f0c0',
                '--canvas-area-bg-edge': '#f2e5bc',
                '--hover-bg': '#d5c4a1',
                '--hover-border': '#bdae93',
            },
            canvas: { bg: '#fbf1c7', dot: '#d5c4a1' },
        },
    },
    nord: {
        label: 'Nord',
        hasLightDark: true,
        dark: {
            ui: {
                '--bg-color': '#2E3440',
                '--toolbar-bg': '#3B4252',
                '--toolbar-bg-end': '#333b4a',
                '--toolbar-hover': '#434C5E',
                '--text-color': '#ECEFF4',
                '--text-muted': '#D8DEE9',
                '--accent-color': '#88C0D0',
                '--accent-hover': '#8FBCBB',
                '--accent-gradient-end': '#6aafc0',
                '--border-color': '#4C566A',
                '--danger-color': '#BF616A',
                '--canvas-area-bg-center': '#2E3440',
                '--canvas-area-bg-edge': '#242933',
                '--hover-bg': '#4C566A',
                '--hover-border': '#5a6578',
            },
            canvas: { bg: '#ECEFF4', dot: '#D8DEE9' },
        },
        light: {
            ui: {
                '--bg-color': '#ECEFF4',
                '--toolbar-bg': '#E5E9F0',
                '--toolbar-bg-end': '#dde1e8',
                '--toolbar-hover': '#D8DEE9',
                '--text-color': '#2E3440',
                '--text-muted': '#4C566A',
                '--accent-color': '#5E81AC',
                '--accent-hover': '#81A1C1',
                '--accent-gradient-end': '#4f7199',
                '--border-color': '#D8DEE9',
                '--danger-color': '#BF616A',
                '--canvas-area-bg-center': '#E9ECF2',
                '--canvas-area-bg-edge': '#E5E9F0',
                '--hover-bg': '#CDD4E0',
                '--hover-border': '#B8C1D0',
            },
            canvas: { bg: '#ECEFF4', dot: '#D8DEE9' },
        },
    },
    onedark: {
        label: 'One Dark',
        hasLightDark: false,
        ui: {
            '--bg-color': '#282c34',
            '--toolbar-bg': '#21252b',
            '--toolbar-bg-end': '#1c1f25',
            '--toolbar-hover': '#2c313a',
            '--text-color': '#abb2bf',
            '--text-muted': '#5c6370',
            '--accent-color': '#61afef',
            '--accent-hover': '#c678dd',
            '--accent-gradient-end': '#4d9ae0',
            '--border-color': '#3e4452',
            '--danger-color': '#e06c75',
            '--canvas-area-bg-center': '#282c34',
            '--canvas-area-bg-edge': '#1e2228',
            '--hover-bg': '#3e4452',
            '--hover-border': '#4b5363',
        },
        canvas: { bg: '#fafafa', dot: '#d0d0d0' },
    },
};
